// This file is auto-generated from apps/server/src/types/router.ts
// Do not edit this file directly. Run 'pnpm generate:types' to regenerate.

// Standalone AppRouter type definition for client consumption
export interface AppRouter {
  auth: {
    getSession: {
      query: () => Promise<any>;
    };
    signUp: {
      mutate: (input: { email: string; password: string; name: string }) => Promise<any>;
    };
    signIn: {
      mutate: (input: { email: string; password: string }) => Promise<any>;
    };
    signOut: {
      mutate: () => Promise<any>;
    };
  };
  health: {
    check: {
      query: () => Promise<{
        status: string;
        timestamp: string;
        checks: Record<string, any>;
      }>;
    };
  };
  portfolio: {
    getPortfolio: {
      query: () => Promise<any>;
    };
    getTransactions: {
      query: () => Promise<any>;
    };
  };
  vault: {
    getVaultInfo: {
      query: () => Promise<any>;
    };
    getVaultOperations: {
      query: () => Promise<any>;
    };
  };
  analytics: {
    getPerformanceMetrics: {
      query: () => Promise<any>;
    };
  };
  ai: {
    getRecommendations: {
      query: () => Promise<any>;
    };
  };
  bridge: {
    getQuote: {
      query: (input: any) => Promise<any>;
    };
  };
  admin: {
    getStats: {
      query: () => Promise<any>;
    };
  };
  staking: {
    getStakingOverview: {
      query: () => Promise<any>;
    };
  };
  governance: {
    getProposals: {
      query: () => Promise<any>;
    };
  };
}
