#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

// This script generates type definitions from the server app for client consumption
// It creates a types file in the common package that can be imported by the web app

const serverTypesPath = path.join(__dirname, '../apps/server/src/types/router.ts');
const commonTypesPath = path.join(__dirname, '../packages/common/src/types/router.generated.ts');

// Read the server router types
const serverTypes = fs.readFileSync(serverTypesPath, 'utf8');

// Generate the common types file with corrected import path
const correctedTypes = serverTypes.replace(
  "import type { appRouter } from '../routers';",
  "import type { appRouter } from '../../../../apps/server/src/routers';"
);

const generatedTypes = `// This file is auto-generated from apps/server/src/types/router.ts
// Do not edit this file directly. Run 'pnpm generate:types' to regenerate.

${correctedTypes}
`;

// Ensure the directory exists
fs.mkdirSync(path.dirname(commonTypesPath), { recursive: true });

// Write the generated file
fs.writeFileSync(commonTypesPath, generatedTypes);

console.log('✅ Generated types from server to packages/common/src/types/router.generated.ts');
