[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
via_ir = true
cbor_metadata = true
gas_reports = ["*"]
auto_detect_solc = false
solc_version = "0.8.28"

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Enable fs permissions for Tenderly
fs_permissions = [
    { access = "read", path = "out/" },
    { access = "read", path = "lib/foundry-chainlink-toolkit/out/" },
]

# RPC endpoints
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
tenderly = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}"

# Etherscan verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# Tenderly verification endpoint
tenderly = { key = "${TENDERLY_ACCESS_TOKEN}", chain = 73571, url = "${TENDERLY_VIRTUAL_TESTNET_RPC_URL}/verify/etherscan" }
# Test configuration
[profile.test]
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
