name: Foundry CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup

      - name: Install dependencies
        run: |
          cd packages/contracts/foundry
          forge install

      - name: Run all tests (unit, fuzz, invariants) and save gas report
        run: |
          cd packages/contracts/foundry
          ~/.foundry/bin/forge test --gas-report > gas-report.txt

      - name: Check for gas regressions
        run: |
          cd packages/contracts/foundry
          ~/.foundry/bin/forge snapshot --check

      - name: Save new gas snapshot (if check passes)
        if: success()
        run: |
          cd packages/contracts/foundry
          ~/.foundry/bin/forge snapshot

      - name: Upload gas report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: packages/contracts/foundry/gas-report.txt
