name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.packages }}
      web: ${{ steps.filter.outputs.web }}
      server: ${{ steps.filter.outputs.server }}
      contracts: ${{ steps.filter.outputs.contracts }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            packages:
              - 'packages/**'
            web:
              - 'apps/web/**'
              - 'packages/**'
            server:
              - 'apps/server/**'
              - 'packages/**'
            contracts:
              - 'packages/contracts/**'

  # Fast Biome checks (formatting and linting)
  biome-check:
    needs: changes
    if: ${{ needs.changes.outputs.packages == 'true' || needs.changes.outputs.web == 'true' || needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Cache Biome binary for faster subsequent runs
      - name: Cache Biome
        uses: actions/cache@v4
        with:
          path: ~/.cache/biome
          key: ${{ runner.os }}-biome-${{ hashFiles('**/biome.json') }}
          restore-keys: |
            ${{ runner.os }}-biome-
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          
      - run: pnpm install --frozen-lockfile
      
      # Fast Biome CI check (includes formatting, linting, and import sorting)
      - name: Biome CI Check
        run: pnpm run check:ci
        
      # Report formatting issues as annotations
      - name: Check Formatting
        if: failure()
        run: |
          echo "::error::Code formatting issues detected. Run 'pnpm run format' to fix."
          pnpm run format:check

  lint-and-typecheck:
    needs: [changes, biome-check]
    if: ${{ needs.changes.outputs.packages == 'true' || needs.changes.outputs.web == 'true' || needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build packages
        run: |
          cd packages/common && pnpm run build
          cd ../contracts && pnpm run build
      - name: Type check
        run: pnpm run check-types
      - name: Test
        run: pnpm run test

  test-contracts:
    needs: changes
    if: ${{ needs.changes.outputs.contracts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build packages
        run: |
          cd packages/common && pnpm run build
          cd ../contracts && pnpm run build
      - name: Type check contracts
        run: pnpm run check-types

  test-e2e:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build packages
        run: |
          cd packages/common && pnpm run build
          cd ../contracts && pnpm run build
      - name: Install Playwright browsers
        run: pnpx playwright install --with-deps
      - name: Run E2E tests
        working-directory: ./apps/web
        run: pnpm run test:e2e
