name: Main CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # Smart Contract Tests
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          cd packages/contracts/foundry
          forge install

      - name: Run tests
        run: |
          cd packages/contracts/foundry
          forge test -vvv

      - name: Generate gas report
        run: |
          cd packages/contracts/foundry
          forge test --gas-report

  # Web Application Tests
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies with Bun
        run: bun install

      - name: Lint web app
        run: |
          cd apps/web
          bun run lint

      - name: Type check web app
        run: |
          cd apps/web
          bun run check-types

      - name: Test web app
        run: |
          cd apps/web
          bun run test

      - name: Build web app
        run: |
          cd apps/web
          bun run build

  # Server Application Tests
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Type check server app
        run: |
          cd apps/server
          bun run check-types

      - name: Build server app
        run: |
          cd apps/server
          bun run build

  # E2E Tests (only if all other tests pass)
  e2e:
    runs-on: ubuntu-latest
    needs: [web, server]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Install Playwright
        run: |
          cd apps/web
          bunx playwright install --with-deps

      - name: Run E2E tests
        run: |
          cd apps/web
          bun run test:e2e

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report/
