name: Web CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
      - name: Install dependencies
        run: |
          cd apps/web
          bun install
      - name: Lint
        run: |
          cd apps/web
          bun run lint
      - name: Type check
        run: |
          cd apps/web
          bun run check-types
      - name: Unit tests
        run: |
          cd apps/web
          bun run test
      - name: Build
        run: |
          cd apps/web
          bun run build
